version : '2'

networks:
 eth-net:
  external:
   name : eth
   
services:
 db:
  image: 0ef9083d9892
  container_name: mysql
  networks:
   eth-net:
    ipv4_address : 172.18.0.10
  ports:
   - "8086:3306"
  environment: 
   MYSQL_ROOT_PASSWORD: "homerun1004!"
  command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  volumes:
   - ./mysql/:/docker-entrypoint-initdb.d
  restart: always
  
 server:
  image : server
  container_name: server
  networks:
   eth-net:
    ipv4_address : 172.18.0.9
  ports:
   - "3000:3000"
  depends_on:
   - db
  working_dir : /home/back  
  command: /bin/sh -c "npm start"

